[package]
name = "idxrs"
version = "0.1.0"
authors = ["kohtoa15 <kohtoa15@htl-kaindorf.ac.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
